import { create } from 'zustand';

import { concatDocuments } from '../core/operations/merge';
import { trimDocument } from '../core/operations/trim';
import { parseVrma } from '../core/vrma/parser';
import { writeVrma } from '../core/vrma/writer';
import type { AnimationDocument } from '../core/vrma/types';
import { FPS } from './timecode';

/** A segment of the source animation, in source-time seconds. Segments play sequentially. */
export interface Clip {
  id: number;
  in: number;
  out: number;
}

/** Timeline tools, Premiere-style: V = selection, C = razor (click a clip to cut). */
export type TimelineTool = 'select' | 'razor';

let clipIdCounter = 0;
const nextClipId = () => ++clipIdCounter;

/** Don't create/keep segments shorter than this. */
const MIN_CLIP_LENGTH = 0.02;

/** Timeline zoom bounds, in pixels per second. */
const MIN_ZOOM = 20;
const MAX_ZOOM = 1000;

/** Timeline-time positions of every clip boundary (edit points), including 0 and the end. */
function editPoints(clips: Clip[]): number[] {
  const points = [0];
  let t = 0;
  for (const clip of clips) {
    t += clip.out - clip.in;
    points.push(t);
  }
  return points;
}

/** Apply the clip list to the source: trim each segment, concatenate the survivors. */
function buildEditedDocument(source: AnimationDocument, clips: Clip[]): AnimationDocument {
  const parts = clips.map((clip) => trimDocument(source, clip.in, clip.out));
  return parts.reduce((joined, part) => concatDocuments(joined, part));
}

interface StudioState {
  /** Untouched parse of the opened .vrma — clips reference ranges of this. */
  sourceDocument: AnimationDocument | null;
  /** Result of applying the clips — what plays, and what export will write. */
  document: AnimationDocument | null;
  clips: Clip[];
  selectedClipId: number | null;
  tool: TimelineTool;
  /** Magnetic snapping (frame grid + edit points + playhead) for timeline edits. */
  snap: boolean;
  /** Timeline zoom in pixels per second. */
  pixelsPerSecond: number;
  /** Undo/redo history of clip lists (document is derived from them). */
  past: Clip[][];
  future: Clip[][];

  sourceFileName: string | null;
  vrmData: ArrayBuffer | null;
  vrmFileName: string | null;
  /** Bytes the viewport plays — regenerated by writeVrma after every edit. */
  vrmaData: ArrayBuffer | null;
  importError: string | null;
  importWarnings: string[];
  viewportError: string | null;

  isPlaying: boolean;
  playhead: number;
  loop: boolean;
  exportOpen: boolean;

  openVrm: (data: ArrayBuffer, fileName: string) => void;
  openVrma: (data: ArrayBuffer, fileName: string) => void;
  trimClip: (id: number, inTime: number, outTime: number) => void;
  /** Razor cut: split whichever clip covers the given timeline time. */
  splitClipAt: (timelineTime: number) => void;
  splitAtPlayhead: () => void;
  /** Ripple-trim the clip under the playhead: Q removes its head up to the playhead. */
  rippleTrimIn: () => void;
  /** Ripple-trim the clip under the playhead: W removes its tail from the playhead. */
  rippleTrimOut: () => void;
  deleteSelectedClip: () => void;
  selectClip: (id: number | null) => void;
  setTool: (tool: TimelineTool) => void;
  toggleSnap: () => void;
  setZoom: (pixelsPerSecond: number) => void;
  /** Move the playhead by whole frames of the editing timebase (pauses playback). */
  stepFrames: (frames: number) => void;
  goToStart: () => void;
  goToEnd: () => void;
  /** Jump the playhead to the previous (-1) or next (+1) edit point. */
  jumpToEdit: (direction: -1 | 1) => void;
  undo: () => void;
  redo: () => void;
  setViewportError: (error: string | null) => void;
  setPlaying: (isPlaying: boolean) => void;
  setPlayhead: (playhead: number) => void;
  toggleLoop: () => void;
  setExportOpen: (open: boolean) => void;
}

export const useStudioStore = create<StudioState>()((set, get) => {
  /** Rebuild document + playback bytes for a clip list (shared by edit/undo/redo). */
  const rebuild = (clips: Clip[]) => {
    const source = get().sourceDocument;
    if (!source) return null;
    const document = buildEditedDocument(source, clips);
    return {
      clips,
      document,
      vrmaData: writeVrma(document).buffer as ArrayBuffer,
      playhead: Math.min(get().playhead, document.duration),
      isPlaying: false,
    };
  };

  const commitClips = (clips: Clip[]) => {
    const rebuilt = rebuild(clips);
    if (!rebuilt) return;
    set((state) => ({ ...rebuilt, past: [...state.past, state.clips], future: [] }));
  };

  return {
    sourceDocument: null,
    document: null,
    clips: [],
    selectedClipId: null,
    tool: 'select',
    snap: true,
    pixelsPerSecond: 120,
    past: [],
    future: [],
    sourceFileName: null,
    vrmData: null,
    vrmFileName: null,
    vrmaData: null,
    importError: null,
    importWarnings: [],
    viewportError: null,
    isPlaying: false,
    playhead: 0,
    loop: true,
    exportOpen: false,

    openVrm: (data, fileName) => set({ vrmData: data, vrmFileName: fileName }),

    openVrma: (data, fileName) => {
      try {
        const { document, warnings } = parseVrma(new Uint8Array(data));
        set({
          sourceDocument: document,
          document,
          clips: [{ id: nextClipId(), in: 0, out: document.duration }],
          selectedClipId: null,
          past: [],
          future: [],
          sourceFileName: fileName,
          vrmaData: data,
          importError: null,
          importWarnings: warnings.map((w) => w.message),
          playhead: 0,
          isPlaying: false,
        });
      } catch (error) {
        set({
          sourceDocument: null,
          document: null,
          clips: [],
          selectedClipId: null,
          past: [],
          future: [],
          sourceFileName: fileName,
          vrmaData: null,
          importError: error instanceof Error ? error.message : String(error),
          importWarnings: [],
          playhead: 0,
          isPlaying: false,
        });
      }
    },

    trimClip: (id, inTime, outTime) => {
      const { clips, sourceDocument } = get();
      if (!sourceDocument) return;
      const clampedIn = Math.max(0, inTime);
      const clampedOut = Math.min(sourceDocument.duration, outTime);
      if (clampedOut - clampedIn < MIN_CLIP_LENGTH) return;
      commitClips(clips.map((c) => (c.id === id ? { ...c, in: clampedIn, out: clampedOut } : c)));
    },

    splitClipAt: (timelineTime) => {
      const { clips } = get();
      let start = 0;
      for (const clip of clips) {
        const length = clip.out - clip.in;
        // Only cut when the point falls inside a clip with room for two
        // viable segments — clicks on a boundary are ignored, like Premiere.
        if (timelineTime > start + MIN_CLIP_LENGTH && timelineTime < start + length - MIN_CLIP_LENGTH) {
          const cut = clip.in + (timelineTime - start);
          commitClips(
            clips.flatMap((c) =>
              c.id === clip.id
                ? [
                    { id: nextClipId(), in: c.in, out: cut },
                    { id: nextClipId(), in: cut, out: c.out },
                  ]
                : [c],
            ),
          );
          return;
        }
        start += length;
      }
    },

    splitAtPlayhead: () => get().splitClipAt(get().playhead),

    rippleTrimIn: () => {
      const { clips, playhead } = get();
      let start = 0;
      for (const clip of clips) {
        const length = clip.out - clip.in;
        if (playhead > start && playhead < start + length) {
          const nextIn = clip.in + (playhead - start);
          if (clip.out - nextIn < MIN_CLIP_LENGTH) return;
          commitClips(clips.map((c) => (c.id === clip.id ? { ...c, in: nextIn } : c)));
          // The removed head ripples away; the playhead lands on the new edit point.
          set({ playhead: start, selectedClipId: clip.id });
          return;
        }
        start += length;
      }
    },

    rippleTrimOut: () => {
      const { clips, playhead } = get();
      let start = 0;
      for (const clip of clips) {
        const length = clip.out - clip.in;
        if (playhead > start && playhead < start + length) {
          const nextOut = clip.in + (playhead - start);
          if (nextOut - clip.in < MIN_CLIP_LENGTH) return;
          commitClips(clips.map((c) => (c.id === clip.id ? { ...c, out: nextOut } : c)));
          set({ selectedClipId: clip.id });
          return;
        }
        start += length;
      }
    },

    deleteSelectedClip: () => {
      const { clips, selectedClipId } = get();
      if (selectedClipId === null || clips.length <= 1) return;
      commitClips(clips.filter((c) => c.id !== selectedClipId));
      set({ selectedClipId: null });
    },

    selectClip: (selectedClipId) => set({ selectedClipId }),

    setTool: (tool) => set({ tool }),

    toggleSnap: () => set((state) => ({ snap: !state.snap })),

    setZoom: (pixelsPerSecond) =>
      set({ pixelsPerSecond: Math.max(MIN_ZOOM, Math.min(MAX_ZOOM, pixelsPerSecond)) }),

    stepFrames: (frames) => {
      const duration = get().document?.duration ?? 0;
      if (duration <= 0) return;
      const currentFrame = Math.round(get().playhead * FPS);
      const next = Math.max(0, currentFrame + frames) / FPS;
      set({ isPlaying: false, playhead: Math.min(next, duration) });
    },

    goToStart: () => set({ isPlaying: false, playhead: 0 }),

    goToEnd: () => {
      const duration = get().document?.duration ?? 0;
      set({ isPlaying: false, playhead: duration });
    },

    jumpToEdit: (direction) => {
      const { clips, playhead } = get();
      if (clips.length === 0) return;
      const points = editPoints(clips);
      const epsilon = 1e-4;
      const target =
        direction > 0
          ? points.find((p) => p > playhead + epsilon)
          : [...points].reverse().find((p) => p < playhead - epsilon);
      if (target !== undefined) set({ isPlaying: false, playhead: target });
    },

    undo: () => {
      const { past, clips } = get();
      const previous = past[past.length - 1];
      if (!previous) return;
      const rebuilt = rebuild(previous);
      if (!rebuilt) return;
      set((state) => ({ ...rebuilt, past: past.slice(0, -1), future: [clips, ...state.future] }));
    },

    redo: () => {
      const { future, clips } = get();
      const next = future[0];
      if (!next) return;
      const rebuilt = rebuild(next);
      if (!rebuilt) return;
      set((state) => ({ ...rebuilt, future: future.slice(1), past: [...state.past, clips] }));
    },

    setViewportError: (viewportError) => set({ viewportError }),
    setPlaying: (isPlaying) => set({ isPlaying }),
    setPlayhead: (playhead) => set({ playhead: Math.max(0, playhead) }),
    toggleLoop: () => set((state) => ({ loop: !state.loop })),
    setExportOpen: (exportOpen) => set(exportOpen ? { exportOpen, isPlaying: false } : { exportOpen }),
  };
});
